# ==============================
# Configuración del servidor
# ==============================
spring.application.name=data-management-cache
server.port=8080
logging.level.com.giia.datamanagement=DEBUG
# ==============================
# Configuración de Redis
# ==============================
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

datacache.redis.key-prefix=proveedor:
datacache.redis.channel=proveedor-updates



# ==============================
# Configuración de SQL Server con R2DBC
# ==============================
spring.r2dbc.url=r2dbc:mssql://localhost:1433/GestionInventarioDB
spring.r2dbc.username=giia_user
spring.r2dbc.password=giia2025

# ==============================
# Configuración de JPA (opcional si usas Spring Data JPA)
# ==============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==============================
# Logging
# ==============================
logging.level.org.springframework.data.redis=INFO
logging.level.com.tuempresa.datamanagementcache=DEBUG
